### ISSUE TITLE
Display the image of the tool in the card view

### ISSUE THREAD

**Issue by demeringo** [Boavizta/ict-sustainability-tools#24]
## Problem

We want to dipslay an image of each tool in the card view.

## Solution

1. Update the content of the logo (in source data) column to contain _only_ a URL of the image to display
2. Configure card view to display this image.

## Additional context or elements

- There is also a possibility to use a second image as a logo positioned just before the title. (to be handled separately See #51 )
- We exclude the storage of images in this repository (and prefer to point to existing external images).

**Comment by fmomo** [comment]
Even when the content of the logo field is made only of an URL (and not "filename(URL)", the logo is not displayed in the Table view...

**Comment by fmomo** [comment]
Why are we excluding image storage in the repository ?

**Comment by demeringo** [comment]
We exclude it in a first step because it means that _we_ have to manage them. Having an external link allow contributors to use the form to change the target image.

Today there is no user friendly way to upload an image to the repo (without creating a PR using git, and we want to avoid external contributors to do so).
