### ISSUE TITLE
DataMi modification process breaks the frictionless/validate check

### ISSUE THREAD

**Issue by fmomo** [Boavizta/ict-sustainability-tools#46]
## Bug description

Whe using Datami/Contribute process, adding a line or modifying an existing one, the frictionless  check fails

## To Reproduce

Adding line
Modifying an existing line

**Comment by fmomo** [comment]
The cause is the fact that the frictionless check implementation is not finished.

**Comment by demeringo** [comment]
I close it now as it should have been fixed by recent fixes like #68, #63 and #64.
