### ISSUE TITLE
No access to frictionless runs reports

### ISSUE THREAD

**Issue by fmomo** [Boavizta/ict-sustainability-tools#47]
## Bug description

When clicking on the link provided by the CI/CD action frictionless/validate, one access to the frictionless dashboard web page, but without relevant content, with the message "Cannot load a report"

## To Reproduce

https://repository.frictionlessdata.io/pages/dashboard.html?user=Boavizta&repo=ict-sustainability-tools&flow=frictionless&run=11520085574

**Comment by demeringo** [comment]
For the time being the only validation workflow implemented does not target the real CSV file.
It was build just to demonstrate the principle (and attemps to validate a different CSV named 
`old-examples/project-list/data/project-list.csv` 

That being said, this does not work (does not display validation results properly, as you mentioned).

1. I will try to make the demo work on the sample data
2. We can then generalize it to the _real_ csv file.

**Comment by demeringo** [comment]
I do not manage to make the report work properly. 

As a workaround, we can access as the uploaded results (artefacts) of an action.
